name: "Automation: Update GH Project"
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  # When a PR is a draft, it should go into "In Progress"
  mark_as_in_progress:
    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'converted_to_draft')
      && github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Update status to in_progress
        uses: github/update-project-action@main
        with:
          github_token: ${{ secrets.GH_PROJECT_AUTOMATION }}
          organization: getsentry
          project_number: 31
          content_id: ${{ github.event.pull_request.node_id }}
          field: Status
          value: "🏗 In Progress"

  # When a PR is not a draft, it should go into "In Review"
  mark_as_in_review:
    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
      && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Update status to in_review
        id: update_status
        uses: github/update-project-action@main
        with:
          github_token: ${{ secrets.GH_PROJECT_AUTOMATION }}
          organization: getsentry
          project_number: 31
          content_id: ${{ github.event.pull_request.node_id }}
          field: Status
          value: "👀 In Review"

  # By default, closed PRs go into "Ready for Release"
  # But if they are closed without merging, they should go into "Done"
  mark_as_done:
    if: |
      github.event.action == 'closed' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Update status to done
        id: update_status
        uses: github/update-project-action@main
        with:
          github_token: ${{ secrets.GH_PROJECT_AUTOMATION }}
          organization: getsentry
          project_number: 31
          content_id: ${{ github.event.pull_request.node_id }}
          field: Status
          value: "✅ Done"

